### PR TITLE
Revert "Update Coffea version to 0.7.22"

### PR DESCRIPTION
**Pull request by oshadura**
Reverts CoffeaTeam/docker-coffea-base#89

### CODE REVIEW

**Comment by lgray** [comment]
something break?

**Comment by oshadura** [comment]
I am trying to understand why pytest got broken after I merged 0.7.22 (I see an xrootd "operation expired" error). Just wanted to make sure everything works as it should.

**Comment by oshadura** [comment]
Looks like EOS is down...
```
>>> uproot.open("root://eospublic.cern.ch//eos/root-eos/cms_opendata_2012_nanoaod/Run2012B_DoubleMuParked.root")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.8/site-packages/uproot/reading.py", line 141, in open
    file = ReadOnlyFile(
  File "/opt/conda/lib/python3.8/site-packages/uproot/reading.py", line 580, in __init__
    self._source = Source(
  File "/opt/conda/lib/python3.8/site-packages/uproot/source/xrootd.py", line 453, in __init__
    self._open()
  File "/opt/conda/lib/python3.8/site-packages/uproot/source/xrootd.py", line 457, in _open
    [
  File "/opt/conda/lib/python3.8/site-packages/uproot/source/xrootd.py", line 458, in <listcomp>
    XRootDResource(self._file_path, self._timeout)
  File "/opt/conda/lib/python3.8/site-packages/uproot/source/xrootd.py", line 83, in __init__
    self._open()
  File "/opt/conda/lib/python3.8/site-packages/uproot/source/xrootd.py", line 92, in _open
    self._xrd_error(status)
  File "/opt/conda/lib/python3.8/site-packages/uproot/source/xrootd.py", line 118, in _xrd_error
    raise OSError(
OSError: XRootD error: [ERROR] Operation expired
in file root://eospublic.cern.ch//eos/root-eos/cms_opendata_2012_nanoaod/Run2012B_DoubleMuParked.root
>>> 
```

**Comment by oshadura** [comment]
EOS is back! I will close this PR and restart GH actions that failed before.

**Pull request closed without merging**
