### PR TITLE
Add fastjet variant of coffea-base

### PR DESCRIPTION
**Pull request by lgray**
This is a temporary solution until the fastjet package is building proper wheels.
No cc7 yet.

I would like the image name format to be `coffeateam/coffea-base:fastjet-$FASTJET_VERSION` but I haven't put that together yet completely, would appreciate some help finishing that off in a nice way.

Cleanups and other suggestions welcome.

### CODE REVIEW

**Comment by lgray** [comment]
Thought of a better way to organize this.

**Comment by lgray** [comment]
We can also just add fastjet to coffea-base and the corresponding updater. It's easy to change back to... Your thoughts?

**Comment by oshadura** [comment]
@lgray wow amazing work! 

I am thinking enabling fastjet in coffea-base image could be interesting for early users of this package as well AF users unless you think it is not ready for wider public and could be just enable it in separate image.

**Comment by lgray** [comment]
The fastjet python package itself it's already pretty good. It's certain to evolve but it's miles better than anything claiming to be equivalent. The only major issue is that it is really hard to install right now (and needs some special care to compile on centos which I haven't done yet).

It's not a small package. It's about 50 MB extra on the image, I'm not sure if that really matters in the grand scheme of things.

**Comment by oshadura** [comment]
I think then we definitely should add it to base image since it is easiest way make this package available at AFs. No worries about Centos, I will add fasjet support there.

**Review by oshadura — APPROVED** [review]

**Pull request merged**
